### ISSUE TITLE
[feature/redis-cache] redis cache를 이용한 중복 상품 이름 검사 기능

### ISSUE THREAD

**Issue by Parksojeongjeong** [f-lab-edu/JBLY#121]
## 기능

- multi-row insert를 이용해 데이터를 insert 할 때 중복된 상품이 있는지 확인하는 쿼리에서 발생하는 네트워크I/O 작업 비용을 줄이기 위해 redis cache를 이용한다.
- Redis Cache이용해서 중복 상품을 검사한 후 insert하는 방식으로 구조를 변경하면 여러차례 발생할 네트워크I/O 를 줄일 수 있고, 예외 상황으로 인해 트랜잭션 롤백되는 상황 방지할 수 있다.

**Comment by EcoFriendlyAppleSu** [comment]
Redis cache를 사용해 중복 데이터처리하는 것이 최선인지 고민이됩니다.
jbly crawling application은 매 자정마다 실행됩니다. 그럴때마다 cloud에서 데이터를 퍼와 Redis에 데이터를 넣고 사용하는 것은 불필요한 작업이 아닐까요? 🤔

**Comment by EcoFriendlyAppleSu** [comment]
상품 이름을 기준으로 중복된 데이터 체크를 진행하고 있는 중 문제를 마주했습니다.

상품이름이 : "XXX XXX XXX - [업뎃중]"으로 올라와있고 쇼핑몰에서 상품이 업데이트 되면 "XXX XXX XXX"로 변경되는 것을 발견했습니다.

상품 이름으로 중복 체크를 할 경우 위 상황은 같은 상품임에도 불구하고 다른 상품으로 인식됩니다. 해결방안으로 상품 이름 대신 상품의 image_url을 기준으로 중복 체크하는 방법을 적용해 개발하고 있습니다. 더 좋은 방법이 생각나신다면 알려주세요!

**Comment by EcoFriendlyAppleSu** [comment]
상품 중복을 처리하기 위해 image 주소 데이터와 상품 타입을 text file에 적어 사용합니다.
개별 데이터 건을 개행을 통해 구분합니다.
