### ISSUE TITLE
[infra/redis] Redis 세션 클러스터링

### ISSUE THREAD

**Issue by Parksojeongjeong** [f-lab-edu/JBLY#17]
🍎 인가 처리 시 NCP에 존재하는 Session table에서 인가 정보를 처리하는 것이 아닌 Redis nosql을 사용해 인가 처리를 수행합니다.

📝 Redis를 사용하는 이유는 아래와 같습니다.

- Redis는 InMemory DB로 빠른 Access를 제공합니다. Redis는 메모리 내에서 데이터를 저장하고 읽기 때문에 디스크 Access에 비해 속도가 빠릅니다. 결과적으로 웹 애플리케이션의 응답 시간을 줄일 수 있습니다.
    - JBLY Project에선 위와 같은 이유로 도입해 사용합니다.

- 그 외에 Redis를 사용할 경우. 웹 애플리케이션의 확장성, 지속성 및 유연성을 향상시킬 수 있습니다.

**Comment by EcoFriendlyAppleSu** [comment]
redis Infra 작업 시 @configuration을 읽지 못해 Test가 깨지는 현상이 발생합니다.

Product 코드 라인에서 Bean 설정 정보를 등록하면 통합 테스트 시 어떤 과정이 있는지 확인해야합니다.
