### ISSUE TITLE
[feature/concurrent-future] multi-process, multi-thread를 이용해 크롤링 병렬 처리하기

### ISSUE THREAD

**Issue by Parksojeongjeong** [f-lab-edu/JBLY#66]
## 고민해 볼 내용

크롤링 하는 시간이 너무 오래 걸리는데 해결 할 수 있는 방법을 찾아야 함.
Redis Cache도 함께 알아볼 것.
병렬 프로그래밍은 순서 보장이 안됨

**Comment by EcoFriendlyAppleSu** [comment]
이 이슈 처리하면서 time package 사용해 크롤링 병렬 처리 전/후 비교한 자료 남기면 좋을 것 같습니다. 👍
