### ISSUE TITLE
[chore/codestyle] python 변수명 스네이크 케이스로 변환

### ISSUE THREAD

**Issue by Parksojeongjeong** [f-lab-edu/JBLY#83]
현재 카멜케이스로 적용되어있는 프로젝트를 파이썬에서 권장하는 스네이크 케이스로 변환합니다.

**Comment by Parksojeongjeong** [comment]
제가 하고있는 작업이 아직 안끝나서 그 작업 마무리되면 제가 닫겠습니다~

**Comment by EcoFriendlyAppleSu** [comment]
혹시 파일 이름도 전부 스네이크 케이스로 변경하나요?

**Comment by Parksojeongjeong** [comment]
`Use CapWords for class names, but lower_with_under.py for module names. Although there are some old modules named CapWords.py, this is now discouraged because it’s confusing when the module happens to be named after a class. (“wait – did I write import StringIO or from StringIO import StringIO?”)`

넹
