### ISSUE TITLE
[feature/img-filtering] 상품 카테고리와 관련 없는 이미지 필터링 기능

### ISSUE THREAD

**Issue by Parksojeongjeong** [f-lab-edu/JBLY#87]
상품 상세 페이지에 상품 카테고리와 다른 이미지나 관련이 없는 이미지가 포함되어있을 수 있다.
상품 카테고리와 일치하지 않는 이미지는 필터링되어야 한다.

**Comment by EcoFriendlyAppleSu** [comment]
해당 이미지는 어떤 이유때문에 필터링이 되어야 하는 건가요?
1. 학습 시킬 데이터로 사용
2. 상세 페이지에 포함되면 안되는 이미지로 판단

**Comment by Parksojeongjeong** [comment]
2번은 페이징 할 때 말씀하시는 건가요? 
노이즈가 될 수 있기 때문에 초반에 학습시킬 때는 최대한 필터링 해야할 것 같다고 판단했었는데요, 생각해보니까 노이즈가 있는 것도 제대로 학습 했는지 판단할 지표가 될 것 같아서 어느정도는 필요하다고 생각이 듭니다.

다만, 모어체리 쇼핑몰의 경우에 똑같은 사진을 여러 카테고리에 넣어두는 방식을 사용하는 것 같아서 그 부분은 얘기 나눠보면 좋을 것 같습니다!

**Comment by EcoFriendlyAppleSu** [comment]
👍

**Comment by Parksojeongjeong** [comment]
어제 말씀하신 open cv관련해서도 더 찾아보고 아이디어 생각나면 바로 말씀 드리겠습니당~
